# Generated by Django 4.0.2 on 2022-02-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_textarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='textarea',
            field=models.CharField(max_length=1000, verbose_name='Поле для отчета'),
        ),
    ]
