# Generated by Django 4.0.2 on 2022-02-11 00:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_note_textarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='textarea',
            field=tinymce.models.HTMLField(),
        ),
    ]
