# Generated by Django 4.0.2 on 2022-02-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_note_textarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='textarea',
            field=models.TextField(),
        ),
    ]
