# Generated by Django 4.0.2 on 2022-02-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_alter_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
    ]
