# Generated by Django 4.0.2 on 2022-02-14 22:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_remove_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='textarea',
            field=tinymce.models.HTMLField(max_length=20000, verbose_name='Поле для отчета'),
        ),
    ]
