# Generated by Django 4.0.2 on 2022-02-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_alter_note_textarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='status',
        ),
    ]
